services:
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ecommerce_data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./product_data:/product_data
     # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce_network

  api:
    build: ./api
    container_name: fastapi_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@postgres/ecommerce_data
    networks:
      - ecommerce_network
    ports:
      - "8000:8000"

  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
